### ISSUE TITLE
perception: output database evaluation result

### ISSUE THREAD

**Issue by hayato-m126** [tier4/driving_log_replayer#16]
The current implementation only outputs evaluation results for each dataset, even if multiple datasets are described in the perception.
In database evaluation, we would like to output the results of multiple datasets together.

**Comment by hayato-m126** [comment]
PR #17 outputs database_result.json but node exit with failure 1

```shell
Updating DataFrame: 100%|████████████████████| 116/116 [00:01<00:00, 103.29it/s]
Updating DataFrame: 100%|█████████████████████| 114/114 [00:01<00:00, 88.15it/s]
Traceback (most recent call last):
  File "/home/hyt/ros_ws/x2/install/driving_log_replayer/lib/driving_log_replayer/perception_database_result_node.py", line 69, in <module>
    main()
  File "/home/hyt/ros_ws/x2/install/driving_log_replayer/lib/driving_log_replayer/perception_database_result_node.py", line 63, in main
    rclpy.spin(perception_database_result)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 218, in spin
    executor = get_global_executor() if executor is None else executor
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 102, in get_global_executor
    __executor = SingleThreadedExecutor()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 700, in __init__
    super().__init__(context=context)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 157, in __init__
    self._guard = GuardCondition(
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/guard_condition.py", line 23, in __init__
    with self._context.handle:
AttributeError: __enter__
Exception ignored in: <function Executor.__del__ at 0x7f6abf608c10>
Traceback (most recent call last):
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 228, in __del__
    if self._sigint_gc is not None:
AttributeError: 'SingleThreadedExecutor' object has no attribute '_sigint_gc'
[ros2run]: Process exited with failure 1
```
