### ISSUE TITLE
NDT Localization Evaluation simulation: Autoware does not start( cannot import name 'InitializeLocalization' from 'tier4_localization_msgs.srv' )

### ISSUE THREAD

**Issue by sgNicola** [tier4/driving_log_replayer#519]
Hi, I have followed the instructions on the quick start for the NDT Localization Evaluation [https://tier4.github.io/driving_log_replayer/quick_start/localization/](url). When I run the simulation with this command : 
`/dlr simulation run -p localization  -l play_rate:=0.5,` Autoware does not start. And there are ERRORs that the localization_evaluator_node cannot import InitializeLocallization:
```[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/sensing/lidar/top/ring_outlier_filter' in container '/sensing/lidar/top/pointcloud_preprocessor/pointcloud_container'
[localization_evaluator_node.py-54] Traceback (most recent call last):
[localization_evaluator_node.py-54]   File "/home/cityuadapt/autoware/install/driving_log_replayer/lib/driving_log_replayer/localization_evaluator_node.py", line 24, in <module>
[localization_evaluator_node.py-54]     from driving_log_replayer.evaluator import DLREvaluator
[localization_evaluator_node.py-54]   File "/home/cityuadapt/autoware/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/evaluator.py", line 46, in <module>
[localization_evaluator_node.py-54]     from tier4_localization_msgs.srv import InitializeLocalization
[localization_evaluator_node.py-54] ImportError: cannot import name 'InitializeLocalization' from 'tier4_localization_msgs.srv' (/home/cityuadapt/autoware/install/tier4_localization_msgs/local/lib/python3.10/dist-packages/tier4_localization_msgs/srv/__init__.py)
[ERROR] [localization_evaluator_node.py-54]: process has died [pid 477756, exit code 1, cmd '/home/cityuadapt/autoware/install/driving_log_replayer/lib/driving_log_replayer/localization_evaluator_node.py --ros-args -r __node:=localization_evaluator -r __ns:=/driving_log_replayer -p use_sim_time:=True -p wheel_radius:=0.25 -p wheel_width:=0.12 -p wheel_base:=1.55 -p wheel_tread:=0.87 -p front_overhang:=0.65 -p rear_overhang:=0.6 -p left_overhang:=0.2 -p right_overhang:=0.2 -p vehicle_height:=2.4 -p max_steer_angle:=0.6 --params-file /tmp/launch_params_l4oghdyc'].
[INFO] [launch]: process[%s] was required: shutting down launched system
[INFO] [topic_state_monitor_node-58]: sending signal 'SIGINT' to process[topic_state_monitor_node-58]
[INFO] [component_container-57]: sending signal 'SIGINT' to process[component_container-57]
[INFO] [ros2-56]: sending signal 'SIGINT' to process[ros2-56]
[INFO] [sleep-55]: sending signal 'SIGINT' to process[sleep-55]
[INFO] [node-53]: sending signal 'SIGINT' to process[node-53]
[ERROR] [sleep-55]: process has died [pid 477759, exit code -2, cmd 'sleep 10.0'].
[INFO] [rviz2-52]: sending signal 'SIGINT' to process[rviz2-52]
[INFO] [component_container_mt-51]: sending signal 'SIGINT' to process[component_container_mt-51]
```

**Comment by sgNicola** [comment]
I have checked the files in ~/autoware/install/tier4_localization_msgs/local/lib/python3.10/dist-packages/tier4_localization_msgs/srv, The InitializeLocalization service might not exist in the tier4_localization_msgs.srv module.
![image](https://github.com/user-attachments/assets/4382af76-5bdd-4696-9c49-1937f0ef149d)

And My autoware version is Autoware.Universe humble,
Ubuntu Version is 22.04,
ROS2: humble

**Comment by sgNicola** [comment]
I updated Autoware to the latest version, and this problem is solved.
